let procList = {
    RR : [
        {
            procName : "p0",
            arrivalTime : 0,
            burstTime : 5,
            color : "green",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p1",
            arrivalTime : 1,
            burstTime : 3,
            color : "yellow",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 2,
            burstTime : 8,
            color : "red",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 3,
            burstTime : 6,
            color : "aqua",
            priority:1,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },

    ],
    tested2 : [
        {
            procName : "p0",
            arrivalTime : 8,
            burstTime : 10,
            color : "green",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p1",
            arrivalTime : 7,
            burstTime : 10,
            color : "yellow",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 6,
            burstTime : 8,
            color : "red",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 0,
            burstTime : 2,
            color : "aqua",
            priority:1,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },
        {
            procName : "p4",
            arrivalTime : 0,
            burstTime : 9,
            color : "teal",
            priority:1,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        }
    ],
    tested3 : [
        {
            procName : "p0",
            arrivalTime : 0,
            burstTime : 8,
            color : "green",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p1",
            arrivalTime : 5,
            burstTime : 2,
            color : "yellow",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 1,
            burstTime : 7,
            color : "red",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 6,
            burstTime : 3,
            color : "aqua",
            priority:1,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },
        {
            procName : "p4",
            arrivalTime : 8,
            burstTime : 5,
            color : "teal",
            priority:1,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        }],
    pp : [
        {
            procName : "p1",
            arrivalTime : 0,
            burstTime : 1,
            color : "green",
            priority:2,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 1,
            burstTime : 7,
            color : "yellow",
            priority:6,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 2,
            burstTime : 3,
            color : "red",
            priority:3,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p4",
            arrivalTime : 3,
            burstTime : 6,
            color : "burlywood",
            priority:5,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },
        {
            procName : "p5",
            arrivalTime : 4,
            burstTime : 5,
            color : "darkolivegreen",
            priority:4,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },
        {
            procName : "p6",
            arrivalTime : 5,
            burstTime : 15,
            color : "darkslategray",
            priority:10,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        },
        {
            procName : "p7",
            arrivalTime : 15,
            burstTime : 8,
            color : "goldenrod",
            priority:9,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        }
    ],
    SJF : [
        {
            procName : "p1",
            arrivalTime : 0,
            burstTime : 7,
            color : "green",
            priority:2,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 2,
            burstTime : 4,
            color : "yellow",
            priority:6,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 4,
            burstTime : 1,
            color : "red",
            priority:3,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p4",
            arrivalTime : 5,
            burstTime : 4,
            color : "burlywood",
            priority:5,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        }
    ],
    PNP : [
        {
            procName : "p1",
            arrivalTime : 0,
            burstTime : 5,
            color : "green",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 5,
            isNew: true   
        },
        {
            procName : "p2",
            arrivalTime : 0,
            burstTime : 3,
            color : "yellow",
            priority:2,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 3,
            isNew: true   
        },
        {
            procName : "p3",
            arrivalTime : 0,
            burstTime : 8,
            color : "red",
            priority:1,
            responseTime:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 8,
            isNew: true   
        },
        {
            procName : "p4",
            arrivalTime : 0,
            burstTime : 6,
            color : "burlywood",
            priority:3,
            responseTime:0,
            completionTIme:0,
            turnRoundTime:0,
            waitTime:0,
            remainingTime : 6,
            isNew: true   
        }
    ]
    
    }
